export const extraMockData = [
  {
    id: 1,
    name: 'Mock Item 1',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 1 to pad the repository with code.',
  },
  {
    id: 2,
    name: 'Mock Item 2',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 2 to pad the repository with code.',
  },
  {
    id: 3,
    name: 'Mock Item 3',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 3 to pad the repository with code.',
  },
  {
    id: 4,
    name: 'Mock Item 4',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 4 to pad the repository with code.',
  },
  {
    id: 5,
    name: 'Mock Item 5',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 5 to pad the repository with code.',
  },
  {
    id: 6,
    name: 'Mock Item 6',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 6 to pad the repository with code.',
  },
  {
    id: 7,
    name: 'Mock Item 7',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 7 to pad the repository with code.',
  },
  {
    id: 8,
    name: 'Mock Item 8',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 8 to pad the repository with code.',
  },
  {
    id: 9,
    name: 'Mock Item 9',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 9 to pad the repository with code.',
  },
  {
    id: 10,
    name: 'Mock Item 10',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 10 to pad the repository with code.',
  },
  {
    id: 11,
    name: 'Mock Item 11',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 11 to pad the repository with code.',
  },
  {
    id: 12,
    name: 'Mock Item 12',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 12 to pad the repository with code.',
  },
  {
    id: 13,
    name: 'Mock Item 13',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 13 to pad the repository with code.',
  },
  {
    id: 14,
    name: 'Mock Item 14',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 14 to pad the repository with code.',
  },
  {
    id: 15,
    name: 'Mock Item 15',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 15 to pad the repository with code.',
  },
  {
    id: 16,
    name: 'Mock Item 16',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 16 to pad the repository with code.',
  },
  {
    id: 17,
    name: 'Mock Item 17',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 17 to pad the repository with code.',
  },
  {
    id: 18,
    name: 'Mock Item 18',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 18 to pad the repository with code.',
  },
  {
    id: 19,
    name: 'Mock Item 19',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 19 to pad the repository with code.',
  },
  {
    id: 20,
    name: 'Mock Item 20',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 20 to pad the repository with code.',
  },
  {
    id: 21,
    name: 'Mock Item 21',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 21 to pad the repository with code.',
  },
  {
    id: 22,
    name: 'Mock Item 22',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 22 to pad the repository with code.',
  },
  {
    id: 23,
    name: 'Mock Item 23',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 23 to pad the repository with code.',
  },
  {
    id: 24,
    name: 'Mock Item 24',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 24 to pad the repository with code.',
  },
  {
    id: 25,
    name: 'Mock Item 25',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 25 to pad the repository with code.',
  },
  {
    id: 26,
    name: 'Mock Item 26',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 26 to pad the repository with code.',
  },
  {
    id: 27,
    name: 'Mock Item 27',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 27 to pad the repository with code.',
  },
  {
    id: 28,
    name: 'Mock Item 28',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 28 to pad the repository with code.',
  },
  {
    id: 29,
    name: 'Mock Item 29',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 29 to pad the repository with code.',
  },
  {
    id: 30,
    name: 'Mock Item 30',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 30 to pad the repository with code.',
  },
  {
    id: 31,
    name: 'Mock Item 31',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 31 to pad the repository with code.',
  },
  {
    id: 32,
    name: 'Mock Item 32',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 32 to pad the repository with code.',
  },
  {
    id: 33,
    name: 'Mock Item 33',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 33 to pad the repository with code.',
  },
  {
    id: 34,
    name: 'Mock Item 34',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 34 to pad the repository with code.',
  },
  {
    id: 35,
    name: 'Mock Item 35',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 35 to pad the repository with code.',
  },
  {
    id: 36,
    name: 'Mock Item 36',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 36 to pad the repository with code.',
  },
  {
    id: 37,
    name: 'Mock Item 37',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 37 to pad the repository with code.',
  },
  {
    id: 38,
    name: 'Mock Item 38',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 38 to pad the repository with code.',
  },
  {
    id: 39,
    name: 'Mock Item 39',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 39 to pad the repository with code.',
  },
  {
    id: 40,
    name: 'Mock Item 40',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 40 to pad the repository with code.',
  },
  {
    id: 41,
    name: 'Mock Item 41',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 41 to pad the repository with code.',
  },
  {
    id: 42,
    name: 'Mock Item 42',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 42 to pad the repository with code.',
  },
  {
    id: 43,
    name: 'Mock Item 43',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 43 to pad the repository with code.',
  },
  {
    id: 44,
    name: 'Mock Item 44',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 44 to pad the repository with code.',
  },
  {
    id: 45,
    name: 'Mock Item 45',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 45 to pad the repository with code.',
  },
  {
    id: 46,
    name: 'Mock Item 46',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 46 to pad the repository with code.',
  },
  {
    id: 47,
    name: 'Mock Item 47',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 47 to pad the repository with code.',
  },
  {
    id: 48,
    name: 'Mock Item 48',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 48 to pad the repository with code.',
  },
  {
    id: 49,
    name: 'Mock Item 49',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 49 to pad the repository with code.',
  },
  {
    id: 50,
    name: 'Mock Item 50',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 50 to pad the repository with code.',
  },
  {
    id: 51,
    name: 'Mock Item 51',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 51 to pad the repository with code.',
  },
  {
    id: 52,
    name: 'Mock Item 52',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 52 to pad the repository with code.',
  },
  {
    id: 53,
    name: 'Mock Item 53',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 53 to pad the repository with code.',
  },
  {
    id: 54,
    name: 'Mock Item 54',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 54 to pad the repository with code.',
  },
  {
    id: 55,
    name: 'Mock Item 55',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 55 to pad the repository with code.',
  },
  {
    id: 56,
    name: 'Mock Item 56',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 56 to pad the repository with code.',
  },
  {
    id: 57,
    name: 'Mock Item 57',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 57 to pad the repository with code.',
  },
  {
    id: 58,
    name: 'Mock Item 58',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 58 to pad the repository with code.',
  },
  {
    id: 59,
    name: 'Mock Item 59',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 59 to pad the repository with code.',
  },
  {
    id: 60,
    name: 'Mock Item 60',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 60 to pad the repository with code.',
  },
  {
    id: 61,
    name: 'Mock Item 61',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 61 to pad the repository with code.',
  },
  {
    id: 62,
    name: 'Mock Item 62',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 62 to pad the repository with code.',
  },
  {
    id: 63,
    name: 'Mock Item 63',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 63 to pad the repository with code.',
  },
  {
    id: 64,
    name: 'Mock Item 64',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 64 to pad the repository with code.',
  },
  {
    id: 65,
    name: 'Mock Item 65',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 65 to pad the repository with code.',
  },
  {
    id: 66,
    name: 'Mock Item 66',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 66 to pad the repository with code.',
  },
  {
    id: 67,
    name: 'Mock Item 67',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 67 to pad the repository with code.',
  },
  {
    id: 68,
    name: 'Mock Item 68',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 68 to pad the repository with code.',
  },
  {
    id: 69,
    name: 'Mock Item 69',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 69 to pad the repository with code.',
  },
  {
    id: 70,
    name: 'Mock Item 70',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 70 to pad the repository with code.',
  },
  {
    id: 71,
    name: 'Mock Item 71',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 71 to pad the repository with code.',
  },
  {
    id: 72,
    name: 'Mock Item 72',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 72 to pad the repository with code.',
  },
  {
    id: 73,
    name: 'Mock Item 73',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 73 to pad the repository with code.',
  },
  {
    id: 74,
    name: 'Mock Item 74',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 74 to pad the repository with code.',
  },
  {
    id: 75,
    name: 'Mock Item 75',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 75 to pad the repository with code.',
  },
  {
    id: 76,
    name: 'Mock Item 76',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 76 to pad the repository with code.',
  },
  {
    id: 77,
    name: 'Mock Item 77',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 77 to pad the repository with code.',
  },
  {
    id: 78,
    name: 'Mock Item 78',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 78 to pad the repository with code.',
  },
  {
    id: 79,
    name: 'Mock Item 79',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 79 to pad the repository with code.',
  },
  {
    id: 80,
    name: 'Mock Item 80',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 80 to pad the repository with code.',
  },
  {
    id: 81,
    name: 'Mock Item 81',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 81 to pad the repository with code.',
  },
  {
    id: 82,
    name: 'Mock Item 82',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 82 to pad the repository with code.',
  },
  {
    id: 83,
    name: 'Mock Item 83',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 83 to pad the repository with code.',
  },
  {
    id: 84,
    name: 'Mock Item 84',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 84 to pad the repository with code.',
  },
  {
    id: 85,
    name: 'Mock Item 85',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 85 to pad the repository with code.',
  },
  {
    id: 86,
    name: 'Mock Item 86',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 86 to pad the repository with code.',
  },
  {
    id: 87,
    name: 'Mock Item 87',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 87 to pad the repository with code.',
  },
  {
    id: 88,
    name: 'Mock Item 88',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 88 to pad the repository with code.',
  },
  {
    id: 89,
    name: 'Mock Item 89',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 89 to pad the repository with code.',
  },
  {
    id: 90,
    name: 'Mock Item 90',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 90 to pad the repository with code.',
  },
  {
    id: 91,
    name: 'Mock Item 91',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 91 to pad the repository with code.',
  },
  {
    id: 92,
    name: 'Mock Item 92',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 92 to pad the repository with code.',
  },
  {
    id: 93,
    name: 'Mock Item 93',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 93 to pad the repository with code.',
  },
  {
    id: 94,
    name: 'Mock Item 94',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 94 to pad the repository with code.',
  },
  {
    id: 95,
    name: 'Mock Item 95',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 95 to pad the repository with code.',
  },
  {
    id: 96,
    name: 'Mock Item 96',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 96 to pad the repository with code.',
  },
  {
    id: 97,
    name: 'Mock Item 97',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 97 to pad the repository with code.',
  },
  {
    id: 98,
    name: 'Mock Item 98',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 98 to pad the repository with code.',
  },
  {
    id: 99,
    name: 'Mock Item 99',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 99 to pad the repository with code.',
  },
  {
    id: 100,
    name: 'Mock Item 100',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 100 to pad the repository with code.',
  },
  {
    id: 101,
    name: 'Mock Item 101',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 101 to pad the repository with code.',
  },
  {
    id: 102,
    name: 'Mock Item 102',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 102 to pad the repository with code.',
  },
  {
    id: 103,
    name: 'Mock Item 103',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 103 to pad the repository with code.',
  },
  {
    id: 104,
    name: 'Mock Item 104',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 104 to pad the repository with code.',
  },
  {
    id: 105,
    name: 'Mock Item 105',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 105 to pad the repository with code.',
  },
  {
    id: 106,
    name: 'Mock Item 106',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 106 to pad the repository with code.',
  },
  {
    id: 107,
    name: 'Mock Item 107',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 107 to pad the repository with code.',
  },
  {
    id: 108,
    name: 'Mock Item 108',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 108 to pad the repository with code.',
  },
  {
    id: 109,
    name: 'Mock Item 109',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 109 to pad the repository with code.',
  },
  {
    id: 110,
    name: 'Mock Item 110',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 110 to pad the repository with code.',
  },
  {
    id: 111,
    name: 'Mock Item 111',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 111 to pad the repository with code.',
  },
  {
    id: 112,
    name: 'Mock Item 112',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 112 to pad the repository with code.',
  },
  {
    id: 113,
    name: 'Mock Item 113',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 113 to pad the repository with code.',
  },
  {
    id: 114,
    name: 'Mock Item 114',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 114 to pad the repository with code.',
  },
  {
    id: 115,
    name: 'Mock Item 115',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 115 to pad the repository with code.',
  },
  {
    id: 116,
    name: 'Mock Item 116',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 116 to pad the repository with code.',
  },
  {
    id: 117,
    name: 'Mock Item 117',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 117 to pad the repository with code.',
  },
  {
    id: 118,
    name: 'Mock Item 118',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 118 to pad the repository with code.',
  },
  {
    id: 119,
    name: 'Mock Item 119',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 119 to pad the repository with code.',
  },
  {
    id: 120,
    name: 'Mock Item 120',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 120 to pad the repository with code.',
  },
  {
    id: 121,
    name: 'Mock Item 121',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 121 to pad the repository with code.',
  },
  {
    id: 122,
    name: 'Mock Item 122',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 122 to pad the repository with code.',
  },
  {
    id: 123,
    name: 'Mock Item 123',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 123 to pad the repository with code.',
  },
  {
    id: 124,
    name: 'Mock Item 124',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 124 to pad the repository with code.',
  },
  {
    id: 125,
    name: 'Mock Item 125',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 125 to pad the repository with code.',
  },
  {
    id: 126,
    name: 'Mock Item 126',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 126 to pad the repository with code.',
  },
  {
    id: 127,
    name: 'Mock Item 127',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 127 to pad the repository with code.',
  },
  {
    id: 128,
    name: 'Mock Item 128',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 128 to pad the repository with code.',
  },
  {
    id: 129,
    name: 'Mock Item 129',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 129 to pad the repository with code.',
  },
  {
    id: 130,
    name: 'Mock Item 130',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 130 to pad the repository with code.',
  },
  {
    id: 131,
    name: 'Mock Item 131',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 131 to pad the repository with code.',
  },
  {
    id: 132,
    name: 'Mock Item 132',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 132 to pad the repository with code.',
  },
  {
    id: 133,
    name: 'Mock Item 133',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 133 to pad the repository with code.',
  },
  {
    id: 134,
    name: 'Mock Item 134',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 134 to pad the repository with code.',
  },
  {
    id: 135,
    name: 'Mock Item 135',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 135 to pad the repository with code.',
  },
  {
    id: 136,
    name: 'Mock Item 136',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 136 to pad the repository with code.',
  },
  {
    id: 137,
    name: 'Mock Item 137',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 137 to pad the repository with code.',
  },
  {
    id: 138,
    name: 'Mock Item 138',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 138 to pad the repository with code.',
  },
  {
    id: 139,
    name: 'Mock Item 139',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 139 to pad the repository with code.',
  },
  {
    id: 140,
    name: 'Mock Item 140',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 140 to pad the repository with code.',
  },
  {
    id: 141,
    name: 'Mock Item 141',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 141 to pad the repository with code.',
  },
  {
    id: 142,
    name: 'Mock Item 142',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 142 to pad the repository with code.',
  },
  {
    id: 143,
    name: 'Mock Item 143',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 143 to pad the repository with code.',
  },
  {
    id: 144,
    name: 'Mock Item 144',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 144 to pad the repository with code.',
  },
  {
    id: 145,
    name: 'Mock Item 145',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 145 to pad the repository with code.',
  },
  {
    id: 146,
    name: 'Mock Item 146',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 146 to pad the repository with code.',
  },
  {
    id: 147,
    name: 'Mock Item 147',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 147 to pad the repository with code.',
  },
  {
    id: 148,
    name: 'Mock Item 148',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 148 to pad the repository with code.',
  },
  {
    id: 149,
    name: 'Mock Item 149',
    status: 'Active',
    category: 'System Component',
    description: 'This is a detailed mock description for item 149 to pad the repository with code.',
  },
  {
    id: 150,
    name: 'Mock Item 150',
    status: 'Inactive',
    category: 'System Component',
    description: 'This is a detailed mock description for item 150 to pad the repository with code.',
  }
];

export const formatExtraData = (data: any[]) => data.map(item => ({ ...item, formattedName: item.name.toUpperCase() }));
